# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_9AOsaf64oB0qiNL4HQMShxALJYX_jt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency


url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Calculate median age for each Pclass
median_ages = df.groupby('Pclass')['Age'].median()

# Fill missing values in Age based on Pclass
df['Age'] = df.apply(lambda row: median_ages[row['Pclass']] if pd.isnull(row['Age']) else row['Age'], axis=1)

df['Cabin'] = df['Cabin'].fillna('not found')

df['Embarked'] = df['Embarked'].fillna('none')

def categorize_age(age):
    if age <= 15:
        return 'Child'
    elif age <= 30:
        return 'YoungAdult'
    elif age <= 45:
        return 'Adult'
    elif age <= 60:
        return 'Middle Aged'
    else:
        return 'Senior'


df['AgeCategory'] = df['Age'].apply(categorize_age)



df['FamilySize'] = df['SibSp'] + df['Parch'] + 1


df['Deck'] = df['Cabin'].str[0]
df['Deck'] = df['Deck'].fillna('Unknown')  # Handle missing values


# Calculate survival rate by class
survival_by_class = df.groupby('Pclass')['Survived'].mean()
print("Survival Rates by Passenger Class:\n", survival_by_class)


# Calculate survival rate by gender
survival_by_gender = df.groupby('Sex')['Survived'].mean()
print("\nSurvival Rates by Gender:\n", survival_by_gender)


# Calculate survival rate by age category
survival_by_age_category = df.groupby('AgeCategory')['Survived'].mean()
print("\nSurvival Rates by Age Category:\n", survival_by_age_category)



# Calculate survival rate by deck
survival_by_deck = df.groupby('Deck')['Survived'].mean()
print("\nSurvival Rates by Deck:\n", survival_by_deck)


# Calculate survival rate by port of embarkation
survival_by_embarked = df.groupby('Embarked')['Survived'].mean()
print("\nSurvival Rates by Port of Embarkation:\n", survival_by_embarked)



# Group by FamilySize and calculate survival rates
survival_by_family_size = df.groupby('FamilySize')['Survived'].mean()
print("Survival Rates by Family Size:\n", survival_by_family_size)




# Survival rate for passengers traveling alone
survival_alone = df[df['FamilySize'] == 1]['Survived'].mean()
print(f"Survival Rate for Passengers Traveling Alone: {survival_alone:.2f}")



# Pivot table: Survival rates by class and gender
pivot_class_gender = pd.pivot_table(df, values='Survived', index='Pclass', columns='Sex', aggfunc='mean')
print("Survival Rates by Class and Gender:\n", pivot_class_gender)


# Pivot table: Survival rates by age group and class
pivot_age_class = pd.pivot_table(df, values='Survived', index='AgeCategory', columns='Pclass', aggfunc='mean')
print("\nSurvival Rates by Age Group and Class:\n", pivot_age_class)


# Pivot table: Survival rates by deck and class
pivot_deck_class = pd.pivot_table(df, values='Survived', index='Deck', columns='Pclass', aggfunc='mean')
print("\nSurvival Rates by Deck and Class:\n", pivot_deck_class)



# Calculate the correlation coefficient
correlation = df['Fare'].corr(df['Survived'])
print(f"Correlation between Fare and Survival: {correlation:.2f}")



#This plot will show how survival rates varied by passenger class and gender, highlighting disparities.
plt.figure(figsize=(8, 6))
sns.barplot(x='Pclass', y='Survived', hue='Sex', data=df, ci=None, palette='viridis')
plt.title('Survival Distribution by Passenger Class and Gender')
plt.xlabel('Passenger Class')
plt.ylabel('Survival Rate')
plt.legend(title='Gender')
plt.show()



#This plot compares the age distribution of passengers who survived and those who did not.
plt.figure(figsize=(10, 6))
sns.histplot(df[df['Survived'] == 1]['Age'], bins=30, kde=True, color='green', label='Survived')
sns.histplot(df[df['Survived'] == 0]['Age'], bins=30, kde=True, color='red', label='Did Not Survive')
plt.title('Age Distribution: Survivors vs Non-Survivors')
plt.xlabel('Age')
plt.ylabel('Count')
plt.legend()
plt.show()



#This plot shows how fare amounts differed between survivors and non-survivors.
plt.figure(figsize=(10, 6))
sns.boxplot(x='Survived', y='Fare', data=df, palette='coolwarm')
plt.title('Fare Distribution by Survival Status')
plt.xlabel('Survived')
plt.ylabel('Fare')
plt.xticks(ticks=[0, 1], labels=['Did Not Survive', 'Survived'])
plt.show()



#This plot examines how family size influenced survival.
plt.figure(figsize=(8, 6))
sns.barplot(x='FamilySize', y='Survived', data=df, palette='muted', ci=None)
plt.title('Survival Rate by Family Size')
plt.xlabel('Family Size')
plt.ylabel('Survival Rate')
plt.show()

"""# New section"""